"""user_unique_login

Revision ID: 1ba966415b4
Revises: fdbe3c8f1f
Create Date: 2015-12-11 03:28:36.664052

"""

# revision identifiers, used by Alembic.
revision = '1ba966415b4'
down_revision = 'fdbe3c8f1f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['login'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
