"""article_unique_systemName_and_path

Revision ID: 2722b0d689c
Revises: 57074be438d
Create Date: 2015-12-31 08:05:52.966358

"""

# revision identifiers, used by Alembic.
revision = '2722b0d689c'
down_revision = '57074be438d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['systemName'])
    op.create_unique_constraint(None, 'articles', ['path'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_constraint(None, 'articles', type_='unique')
    ### end Alembic commands ###
