"""user_vk_id_is_unique

Revision ID: 32846275520
Revises: 
Create Date: 2015-08-19 06:30:13.320735

"""

# revision identifiers, used by Alembic.
revision = '32846275520'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['vk_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
