"""goods

Revision ID: 3487fa86e0a
Revises: 2722b0d689c
Create Date: 2016-01-21 14:16:39.635050

"""

# revision identifiers, used by Alembic.
revision = '3487fa86e0a'
down_revision = '2722b0d689c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('isEgood', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('filePath', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    ### end Alembic commands ###
