"""payment_system_begin

Revision ID: 3ef35b74884
Revises: 11cf1e4d2de
Create Date: 2016-03-17 06:07:09.677717

"""

# revision identifiers, used by Alembic.
revision = '3ef35b74884'
down_revision = '11cf1e4d2de'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(precision=2), nullable=True),
    sa.Column('paid_amount', sa.Float(precision=2), nullable=True),
    sa.Column('rejected_amount', sa.Float(precision=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_good',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('payment_failed', 'excluded', 'created', 'refund_failed', 'refund_began', 'paid', 'payment_began', 'refunded', name='enum_order_status', native_enum=False), nullable=True),
    sa.Column('count', sa.Float(precision=4), nullable=True),
    sa.Column('total', sa.Float(precision=2), nullable=True),
    sa.Column('paid_amount', sa.Float(precision=2), nullable=True),
    sa.Column('refund_count', sa.Float(precision=4), nullable=True),
    sa.Column('refund_amount', sa.Float(precision=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['user_.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_good_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_good_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('payment_failed', 'excluded', 'created', 'refund_failed', 'refund_began', 'paid', 'payment_began', 'refunded', name='enum_order_status', native_enum=False), nullable=True),
    sa.Column('paid', sa.Float(precision=2), nullable=True),
    sa.Column('rejected', sa.Float(precision=2), nullable=True),
    sa.Column('shop_money_delta', sa.Float(precision=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_good_id'], ['order_good.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_good_status')
    op.drop_table('order_good')
    op.drop_table('order')
    ### end Alembic commands ###
