"""user_add_email_and_login

Revision ID: 5421692cc2b
Revises: ea1d87bfa4
Create Date: 2015-08-27 01:21:06.554698

"""

# revision identifiers, used by Alembic.
revision = '5421692cc2b'
down_revision = 'ea1d87bfa4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('login', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
