"""article_users_revisions_add_relations

Revision ID: 57074be438d
Revises: 5a8877b6938
Create Date: 2015-12-22 09:24:24.070279

"""

# revision identifiers, used by Alembic.
revision = '57074be438d'
down_revision = '5a8877b6938'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'articles_revisions', 'users', ['authorId'], ['id'])
    op.create_foreign_key(None, 'articles_revisions', 'articles', ['articleId'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles_revisions', type_='foreignkey')
    op.drop_constraint(None, 'articles_revisions', type_='foreignkey')
    ### end Alembic commands ###
