"""article_revision_authorId_fix

Revision ID: 5a8877b6938
Revises: a0e345e837
Create Date: 2015-12-18 05:25:29.545698

"""

# revision identifiers, used by Alembic.
revision = '5a8877b6938'
down_revision = 'a0e345e837'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles_revisions', 'authorId')
    op.add_column('articles_revisions', sa.Column('authorId', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles_revisions', 'authorId')
    op.add_column('articles_revisions', sa.Column('authorId', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
