"""refund_and_money_transaction

Revision ID: 615d69ab1b64
Revises: 964984c87f97
Create Date: 2016-03-29 00:29:34.455242

"""

# revision identifiers, used by Alembic.
revision = '615d69ab1b64'
down_revision = '964984c87f97'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egood_download_link',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('egood_id', sa.Integer(), nullable=True),
        sa.Column('download_code', sa.Text(), server_default='true', nullable=False),
        sa.Column('for_user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires', sa.DateTime(), nullable=False),
        sa.Column('downloads_count', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['egood_id'], ['good.id'], ),
        sa.ForeignKeyConstraint(['for_user_id'], ['user_.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('money_transaction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('error', 'succeed', 'canceled', 'requestSent', 'created', name='enum_money_transaction_status', native_enum=False), nullable=True),
        sa.Column('type', sa.Enum('buy', 'reject', name='enum_money_transaction_type', native_enum=False), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['user_.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user_.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('refund',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('status', sa.Enum('error', 'canceled', 'timeout', 'refunded', 'created', name='enum_refund_status', native_enum=False), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['order_.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user_.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('money_transaction_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('money_transaction_id', sa.Integer(), nullable=True),
        sa.Column('provider', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('error', 'succeed', 'canceled', 'requestSent', 'created', name='enum_order_status', native_enum=False), nullable=True),
        sa.Column('request_data', postgresql.JSON(), nullable=True),
        sa.Column('answer_data', postgresql.JSON(), nullable=True),
        sa.Column('error', postgresql.JSON(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['money_transaction_id'], ['order_good.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user_.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('refund_order_good',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('refund_id', sa.Integer(), nullable=True),
        sa.Column('order_good_id', sa.Integer(), nullable=True),
        sa.Column('count', sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('status', sa.Enum('payment_began', 'refund_began', 'refund_failed', 'excluded', 'paid', 'refunded', 'created', 'payment_failed', name='enum_order_status', native_enum=False), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['order_good_id'], ['order_good.id'], ),
        sa.ForeignKeyConstraint(['refund_id'], ['order_good.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user_.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_order_good')
    op.drop_table('money_transaction_status')
    op.drop_table('refund')
    op.drop_table('money_transaction')
    op.drop_table('egood_download_link')
    ### end Alembic commands ###
