"""order_good_status__add_count

Revision ID: 73b3215993d2
Revises: d118ac47117a
Create Date: 2016-04-20 13:49:00.360855

"""

# revision identifiers, used by Alembic.
revision = '73b3215993d2'
down_revision = 'd118ac47117a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_good_status', sa.Column('count', sa.Numeric(precision=12, scale=4), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_good_status', 'count')
    ### end Alembic commands ###
