"""order_good_status__add_money_transaction_status_id

Revision ID: 92cd6c37e6e2
Revises: 73b3215993d2
Create Date: 2016-04-21 14:07:06.170916

"""

# revision identifiers, used by Alembic.
revision = '92cd6c37e6e2'
down_revision = '73b3215993d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_good_status', sa.Column('money_transaction_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_good_status', 'money_transaction_status', ['money_transaction_status_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_good_status', type_='foreignkey')
    op.drop_column('order_good_status', 'money_transaction_status_id')
    ### end Alembic commands ###
