"""article_active

Revision ID: a0e345e837
Revises: 1ba966415b4
Create Date: 2015-12-11 05:11:51.386391

"""

# revision identifiers, used by Alembic.
revision = 'a0e345e837'
down_revision = '1ba966415b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'active')
    ### end Alembic commands ###
