"""user_add_group

Revision ID: ea1d87bfa4
Revises: 32846275520
Create Date: 2015-08-20 07:10:35.420720

"""

# revision identifiers, used by Alembic.
revision = 'ea1d87bfa4'
down_revision = '32846275520'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group')
    ### end Alembic commands ###
