"""pyragrid_articles_and_revisions

Revision ID: fdbe3c8f1f
Revises: 59ba331f80
Create Date: 2015-12-09 04:46:34.897356

"""

# revision identifiers, used by Alembic.
revision = 'fdbe3c8f1f'
down_revision = '59ba331f80'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('systemName', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('activeRevisionId', sa.Integer(), nullable=True),
    sa.Column('isTemplate', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articleId', sa.Integer(), nullable=False),
    sa.Column('parentRevisionId', sa.Integer(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('authorId', sa.DateTime(), nullable=True),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_index_result')
    op.drop_table('tests')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tests_pkey')
    )
    op.create_table('test_index_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_index_result_pkey')
    )
    op.drop_table('articles_revisions')
    op.drop_table('articles')
    ### end Alembic commands ###
