#!/bin/bash

if [ -z "$1" ]; then
	echo Usage: db-autogen-revision revision_name
	exit
fi

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SERVER_DIR=$(readlink -f ${THIS_DIR}/..)
cd ${SERVER_DIR}
. ${SERVER_DIR}/../venv/bin/activate
alembic revision --autogenerate -m $1