#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SERVER_DIR=$(readlink -f ${THIS_DIR}/..)
SERVER_PACKAGE_DIR=$(readlink -f ${SERVER_DIR}/pyragrid)

source ${THIS_DIR}/db-params.inc.sh

pg_dump --oids --no-owner BestTests > ${SERVER_DIR}/data/${DB_BACKUP_FILE_NAME}