#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${THIS_DIR}/db-params.inc.sh

backup_file_path="${SERVER_DIR}/data/${DB_BACKUP_FILE_NAME}"

#TODO (maybe) PGPASSWORD="..."
pg_dump --oids --no-owner ${DB_NAME} > "${backup_file_path}"
ls -l "${backup_file_path}"