#!/bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SERVER_DIR=$(readlink -f ${THIS_DIR}/..)
cd ${SERVER_DIR}
. ${SERVER_DIR}/venv/bin/activate
source ${THIS_DIR}/db-params.inc.sh
#TODO config from env PYRAGRID_CONFIG_NAME
alembic upgrade head