#!/bin/bash

echo deprecated
exit

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SERVER_DIR=$(readlink -f ${THIS_DIR}/..)
SERVER_DIR=$(readlink -f ${THIS_DIR}/..)
SERVER_PACKAGE_DIR=$(readlink -f ${SERVER_DIR}/pyragrid)

source ${THIS_DIR}/db-params.inc.sh

. ${SERVER_DIR}/../venv/bin/activate
sqlacodegen postgresql://${DB_USER}:${DB_PASSWORD}@localhost/${DB_NAME} > ${SERVER_PACKAGE_DIR}/${MODEL_OUTPUT_FILE_NAME}